# infra/ansible/inventory.ini
# Ce fichier liste les serveurs sur lesquels Ansible va se connecter

[staging]
staging-server ansible_host={{ STAGING_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

# Remplacer STAGING_HOST par l'IP de votre VM OVH
# Exemple : staging-server ansible_host=51.210.xxx.xxx ansible_user=ubuntu ...
